### ISSUE TITLE
List of components

### ISSUE THREAD

**Issue by jmaicaaan** [tinker-hub/docnest-desktop#6]
Can we list down all the components we need here? Then let's have a checklist for us to add in the storybook. I plan to have it done this week.

**Comment by isotopeee** [comment]
Regarding the `shared components`, I think almost all we need is included in the `material-UI` library. We just need to wrap it as `custom components`.

**Comment by jmaicaaan** [comment]
Doing that doesnt really make sense working with the storybook. If we are going to do that approach, the storybook shoudn't be included initially. I think that was the idea why we include the storybook. Did I missed anything?

**Comment by isotopeee** [comment]
I guess your right. What I have in mind right now is to wrap the `material-ui components` that we will need. I shall create a ticket for that.

**Comment by isotopeee** [comment]
I've created #8 based on our discussion. Closing this issue now.
