### ISSUE TITLE
Integration of components

### ISSUE THREAD

**Issue by jmaicaaan** [tinker-hub/docnest-desktop#7]
Planning this to have somehow a little before the end of the week. It is important for us to have this one also get started.

**Comment by isotopeee** [comment]
I think you're referring to the `screens` components/containers here. Let me check on the comps and create the appropriate tickets.

**Comment by jmaicaaan** [comment]
Yes, that is correct. Please list it all here. So we could create epics for those tickets :)

**Comment by jmaicaaan** [comment]
Status?

**Comment by isotopeee** [comment]
🚧 Working on #3
